micronaut:
  application:
    name: gateway
  server:
    port: 8085
    cors:
      enabled: true
    max-request-size: 20MB
  netty:
    max-request-size: 10MB
    event-loops:
      other:
        num-threads: 30
        prefer-native-transport: true
  http:
    client:
      read-timeout: 300s
      max-content-length: 30MB
      event-loop-group: other
    services:
      auth:
        urls:
          - ${AUTH_SERVICE_URL}
        pool:
          enabled:
            max-connections: 50
        read-timeout: 60s
      gallery:
        urls:
          - ${GALLERY_SERVICE_URL}
        pool:
          enabled:
            max-connections: 50
        read-timeout: 300s
      allowance:
        urls:
          - ${ALLOWANCE_SERVICE_URL}
        pool:
          enabled:
            max-connections: 50
        read-timeout: 60s
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            validation:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
      propagation:
        enabled: true
        service-id-regex: "auth|gallery|allowance"
netty:
  default:
    allocator:
      max-order: 3
